name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python syntax check
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m compileall -q .

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: portwatcher:test
