name: Release Image

on:
  push:
    branches: [main]
    tags: ['v*.*.*']  # SemVer-Tags pushen ebenfalls
  schedule:
    - cron: '17 01 * * 2'   # weekly rebuild (Mon 03:17 UTC)

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # optional, wenn du multi-arch bauen willst (arm64 für Raspberry Pi)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # WICHTIG: Buildx als docker-container-Driver
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          # falls du nur amd64 willst: platforms: linux/amd64
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/portwatcher:latest
            ghcr.io/${{ github.repository_owner }}/portwatcher:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # optional: provenance abschalten, wenn du keine SBOM/Attestations brauchst
          # provenance: false
